return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "htmldjango",
      -- "glimmer",
      "vim",
      "lua",
      "html",
      "css",
      "javascript",
      "typescript",
      "tsx",
      "c",
      "markdown",
      "markdown_inline",
      "rust",
      "bash",
      "git_config",
      "gitignore",
      "go",
      "json",
      "proto",
      "python",
      "regex",
      "scss",
      "sql",
      "toml",
      "twig",
      "yaml",
      "xml",
    },
    indent = {
      enable = true,
    },
  },
}
